call plug#begin()

Plug 'tpope/vim-sensible'
Plug 'tpope/vim-obsession'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'junegunn/vim-easy-align'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'junegunn/seoul256.vim'
Plug 'junegunn/goyo.vim'
Plug 'junegunn/limelight.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'edkolev/tmuxline.vim'

call plug#end()

let mapleader = " "

set mouse=a
set hidden
set autoread

colo seoul256
set background=dark

set number
set splitbelow
set splitright

set colorcolumn=80
set textwidth=72

set autoindent
set noexpandtab
set smartindent
set smarttab

set shiftwidth=8
set softtabstop=0
set tabstop=8

set hlsearch
set ignorecase
set smartcase

set wildignorecase
set wildmenu
set wildmode=longest:full,full

set nobackup
set noswapfile
set nowritebackup

function! LeaderEsc()
	" To detect the file type again
	filetype detect
	" To check changes by outside Vim
	checktime
	" To clear the last used search pattern
	let @/ = ""
endfunction

nnoremap <silent> <Leader><Esc> <Cmd>call LeaderEsc()<CR><Cmd>source $MYVIMRC<CR>

" Copy system clipboard in visual mode
xnoremap <Leader>y "+y

" vim-easy-align
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)

" fzf.vim
nnoremap <Leader>ff <Cmd>Files<CR>
nnoremap <Leader>fF <Cmd>Files $HOME<CR>
nnoremap <Leader>bb <Cmd>Buffers<CR>
nnoremap <Leader>bl <Cmd>BLines<CR>
nnoremap <Leader>bL <Cmd>Lines<CR>
nnoremap <Leader>fh <Cmd>Helptags<CR>

" goyo.vim
nnoremap <Leader>gl <Cmd>Goyo<CR>
nnoremap <Leader>gg <Cmd>Goyo<CR><Cmd>Limelight!<CR>

" limelight.vim
autocmd! User GoyoEnter Limelight
autocmd! User GoyoLeave Limelight!

" tmuxline.vim
let g:tmuxline_powerline_separators = 0
let g:tmuxline_preset = 'full'
