call plug#begin()

Plug 'tpope/vim-sensible'
Plug 'tpope/vim-obsession'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'junegunn/vim-easy-align'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'junegunn/goyo.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'edkolev/tmuxline.vim'

call plug#end()

let mapleader = " "

colo lunaperche

set autoread
set hidden
set background=dark
set mouse=a
set numberwidth=5
set scrolloff=5

set number
set splitbelow
set splitright

set colorcolumn=80
set textwidth=72

set autoindent
set noexpandtab
set smartindent
set smarttab

set shiftwidth=8
set softtabstop=0
set tabstop=8

set hlsearch
set ignorecase
set smartcase

set wildignorecase
set wildmenu
set wildmode=longest:full,full

set nobackup
set noswapfile
set nowritebackup

"
" KEYMAP
"

" Clear the last used search pattern
nnoremap <Leader>1 <Cmd>let @/ = ""<CR>
" Detect the file type again
nnoremap <Leader>2 <Cmd>filetype detect<CR>
" Check changes made outside
nnoremap <Leader>3 <Cmd>checktime<CR>
" Source vimrc
nnoremap <Leader>0 <Cmd>source $MYVIMRC<CR>
" Cursor always in the middle
nnoremap <Leader>4 <Cmd>set scrolloff=999<CR>

" Copy in visual mode to clipboard
xnoremap <Leader>y "+y

" vim-easy-align
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)

" fzf.vim
nnoremap <Leader>ff <Cmd>Files<CR>
nnoremap <Leader>fF <Cmd>Files $HOME<CR>
nnoremap <Leader>bb <Cmd>Buffers<CR>
nnoremap <Leader>bl <Cmd>BLines<CR>
nnoremap <Leader>bL <Cmd>Lines<CR>
nnoremap <Leader>fh <Cmd>Helptags<CR>

" goyo.vim
nnoremap <Leader>g <Cmd>Goyo<CR>

" tmuxline.vim
let g:tmuxline_powerline_separators = 0
let g:tmuxline_preset = 'tmux'

"
" Autocmds
"

" Relative line numbers when entering Visual mode
au ModeChanged [vV\x16]*:* let &l:rnu = mode() =~# '^[vV\x16]'
au ModeChanged *:[vV\x16]* let &l:rnu = mode() =~# '^[vV\x16]'
au WinEnter,WinLeave * let &l:rnu = mode() =~# '^[vV\x16]'

" goyo.vim
autocmd! User GoyoEnter set scrolloff=999
autocmd! User GoyoLeave set scrolloff=5
